version: "3.7"

services:

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    init: true
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data: {}
